#!/usr/bin/env bash
# Configure Nginx so that its HTTP response contains a custom header
# HTTP response contains a custom header (on web-01 and web-02)

# Update the package list
sudo apt update

# Install Nginx
sudo apt install -y nginx

# Define the custom header value
custom_header_value="$(hostname)"

# Update the default Nginx configuration file
sudo tee /etc/nginx/sites-available/default <<EOF
server {
    listen 80;
    listen [::]:80;

    server_name _;

    error_page 404 /404.html;
    add_header X-Served-By $custom_header_value;

    location / {
        root /var/www/html;
        index index.html;
    }

    location /redirect_me {
        return 301 https://github.com/robberbadeia;
    }

    location /404 {
        root /var/www/html;
        internal;
    }
    # Remove the duplicate location block
    location /custom_404.html {
        internal;
    }
}
EOF

# Test the Nginx configuration for syntax errors
sudo nginx -t

# Restart Nginx to apply the changes
sudo systemctl restart nginx
